### ISSUE TITLE
Feature Request: Camera placeholder

### ISSUE THREAD

**Issue by Zaid-maker** [Rahuletto/pickr#1]
Add a Camera placeholder where it shows the camera where i am pointing my camera is for better color picking.

Maybe in Bottom Left or Bottom Right and able to get hidden

**Comment by Rahuletto** [comment]
Hmm, was thinking about that too. I'll implement it. Thanks!

**Comment by Zaid-maker** [comment]
> Hmm, was thinking about that too. I'll implement it. Thanks!
> 

Love to see it!

**Comment by Rahuletto** [comment]
https://github.com/Rahuletto/pickr/commit/33c5accb3e2aa5fd2fae3c787937f7c5088aad17 - feat: adding camera feed into it

Adds the feature of displaying the live video feed from the camera to focus without guessing it 👍🏼 
Thanks for the feature request
